use Mix.Config

# Configure your database
config :ssmserver, Ssmserver.Repo,
  username: "postgres",
  password: "postgres",
  database: "ssmserver_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :ssmserver, Ssmserver.Mailer,
  adapter: Bamboo.MailgunAdapter,
  domain: "sandboxf094ee0f815c409c8412ca666f1d1ff7.mailgun.org",
  api_key: "key-654805cea4ad9871aeca247b5745913c",
  base_uri: "https://api.mailgun.net/v3"

# config :ssmserver,
#   domain: "sandboxf094ee0f815c409c8412ca666f1d1ff7.mailgun.org",
#   mailgun_api_key: "pubkey-82c28a7a09f5f28672cfdafe21d20880", #7c320e7c565f8a44af7eb48d33cb5a2f-f135b0f1-cb7a4694
#   base_uri: "https://api.mailgun.net/v3"


# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :ssmserver, SsmserverWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ssmserver, SsmserverWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ssmserver_web/{live,views}/.*(ex)$",
      ~r"lib/ssmserver_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
